### ISSUE TITLE
Adding layers to a LayerSwitcher via dragAndDropInteraction

### ISSUE THREAD

**Issue by WillieMaddox** [Viglino/ol-ext#1059]
Hello,

On startup, I initialize my layer switcher with base maps.  I also have a drag and drop interaction set up for adding GeoJSON, KML, etc.  

Is there a way to add these layers to the layer switcher?  

It would be nice to be able to delete them without having to refresh the browser every time.  Also toggling their visibility on/off would be pretty sweet.

Thanks,

-Willie

**Comment by mike-000** [comment]
OpenLayers DragAndDrop and ol-ext DropFile interactions return features in an `addfeatures` event, it is up to the application to add those to a layer.

A layer constructed with a `title` property (you might want to use the dropped file name) will be added to the top of the LayerSwitcher list

```
  dragAndDropInteraction.on('addfeatures', function (event) {
    const vectorSource = new VectorSource({
      features: event.features,
    });
    map.addLayer(
      new VectorLayer({
        title: event.file.name,
        source: vectorSource,
      }),
    );
    map.getView().fit(vectorSource.getExtent());
  });
```

or you could adjust the layer order and zIndex to add to the opposite end of the list

```
  dragAndDropInteraction.on('addfeatures', function (event) {
    const vectorSource = new VectorSource({
      features: event.features,
    });
    map.getLayers().insertAt(
      0,
      new VectorLayer({
        title: event.file.name,
        zIndex: map.getLayers().getLength(),
        source: vectorSource,
      }),
    );
    map.getView().fit(vectorSource.getExtent());
  });

```
https://codesandbox.io/s/drag-and-drop-forked-rvt75k?file=/main.js

You could also add the layer to an existing LayerGroup instead of directly to the map.

**Comment by WillieMaddox** [comment]
Thanks for the quick reply.  The third option was what I was trying to get working.  Working backwards from your sandbox example I was able to find my error. I just needed to change,
```javascript
layergroup.getLayers().getArray().push(newVectorLayer);
```
to
```javascript
layergroup.getLayers().push(newVectorLayer);
```
and everything worked.

Thanks again!

-W
