### ISSUE TITLE
Some examples not working

### ISSUE THREAD

**Issue by PeterC66** [Viglino/ol-ext#149]
Thanks for these - I will look to use some of them as I move to OL5, but some examples did not do what I expected:

1) On the Animated clusters example at https://viglino.github.io/ol-ext/examples/animation/map.animatedcluster.html and the Clustering example at https://viglino.github.io/ol-ext/examples/map/map.clustering.html I could see no features, and hence no effects.

2) When I tried the Overpass source example it did not load in a reasonable time and used a lot of resources

3) On the Wikimedia Commons layer at https://viglino.github.io/ol-ext/examples/layer/map.wikicommons.html it was not obvious to me where the features were, and they disappeared when I zoomed out. I did eventually see the effect.

**Comment by Viglino** [comment]
Hello,
1.  Examples are working on http not on https because jQuery is included using the http protocol. I'll try to fix it asap. 
You can see it using http instead: http://viglino.github.io/ol-ext/examples/animation/map.animatedcluster.html 
and http://viglino.github.io/ol-ext/examples/map/map.clustering.html 
2. The overpass example is working: http://viglino.github.io/ol-ext/examples/layer/map.overpass.html
But the request is on the overpass server that could be quiet busy sometimes.
3. On the Wikimedia Commons layer the zoom level is limited to prevent large request on the server. Thus only limited features are displayed on zoom > 13. It's just an example to show what can be done.
