### ISSUE TITLE
Translate from Cluster

### ISSUE THREAD

**Issue by nathanashton** [Viglino/ol-ext#156]
Is there any ability to translate a feature out of a Cluster?

I've added a translate interaction to the feature/s that are within a cluster but nothing seems to happen.

Thanks.

**Comment by Viglino** [comment]
Clusters are calculated on features positions. If you translate the feature it wil be recalculated with this position. Maybe you'll hAvé tô refresh the cluster. Be sure you move the original geometry of the feature.

**Comment by nathanashton** [comment]
Adding a translate interaction to the original features doesn't seem to do anything.

The best I can do at the moment is to get the features in the overlay layer from the select cluster interaction when it is expanded. I can add an interaction to these features which lets me drag them when the cluster is expanded.

To make this approach more workable, I need to know the following:

* Is there an event fired I can hook into when the select cluster gets expanded?
* Is there a way to tell the select cluster to collapse?

Thanks for the help

**Comment by Viglino** [comment]
You have to work on the original features, not on the cluster layer or on expended features overlay. Othewise you just move the position of the cluster itself or the position of the expended features that are placed on a circle or a spiral to make them more viewable.  Not the original geometry. 
You have to use a non clustered layer when interacting on features.
Otherwise the clear() function will collapse the cluster and the 'select' event will tell you which feature is selected.

**Comment by Viglino** [comment]
:+1:  Better open a new issue to reflect the problem more clearly.
