### ISSUE TITLE
Creating control bar with multiple class names throws OMException: Failed to execute 'add' on 'DOMTokenList'

### ISSUE THREAD

**Issue by jcachat** [Viglino/ol-ext#202]
With the changes to remove jquery, my map is now broken because I am constructing an ol.control.bar with a "className" parameter that specifies multiple class names.

Now that you are calling "element.classList.add(options.className);", it throws this exception: DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('ol-bottom iq-centered-control-bar-container') contains HTML space characters, which are not valid in tokens.

I'm sure I can work around it by creating a single css class.  But can this be fixed to support multiple class names?

**Comment by ThomasG77** [comment]
Not sure when you expect a className, it's a good idea to provide it multiple classNames semantically because you can :)
However, I've done a fix (referencing this issue).
It seems you also opened #201 with the same issue (where you ask the feature that this issue raises). You may close it to avoid duplication but I could be wrong.
