### ISSUE TITLE
refactoring: typescript

### ISSUE THREAD

**Issue by arszp10** [Viglino/ol-ext#337]
Hey.
I propose to simplify the repository. You can take the project build code from openlayers and rewrite it to a typescript.

If there is interest, I can soon start writing code.

**Comment by Viglino** [comment]
Look at this project: https://github.com/Siedlerchr/types-ol-ext

**Comment by arszp10** [comment]
I saw this repository reading a #335 and #305

[repository](https://github.com/Siedlerchr/types-ol-ext) has a many of bugs.

I think that the assembly and style code can be done in openlayers.

**Comment by Siedlerchr** [comment]
@arszp10  It would be cool if you could help me with the type definitions getting that working

**Comment by kobakazu0429** [comment]
Hello.

This project is (https://github.com/Siedlerchr/types-ol-ext) only declaration typing, right?

I want to rewrite `.js` to `.ts`, because current source is using prototype and normal function.
how would like to this idea ?

if it will realize, I will write typescript code (however I'm javascript beginner...)
