### ISSUE TITLE
ol-ext/control/Toggle :: onToggle doesn't fire when the toggle is set to inactive using JavaScript

### ISSUE THREAD

**Issue by mperdikeas** [Viglino/ol-ext#564]
If I have a toggle and I set it to inactive using JS:

    toggle.setActive(false)

Then its `onToggle` handler doesn't fire. Is this the intended behaviour?
Tested with `3.1.15`

**Comment by Viglino** [comment]
The event is fired on click on the button.
If you activate it programmatically you should know what's to do...

**Comment by Viglino** [comment]
Actually `setActive` activate the interaction placed on the button. 
You can listen to `change:active` event on the interaction to get aware of it.

**Comment by birbilis** [comment]
Indeed usually programmatic interactions don't fire change events in browser-based UIs, probably to avoid loop when 2-way linking items. Only user interactions do. In other UI models one can descend from a control and override the method that fires the event so that they can do something extra in that case, then call the ancestor's method to notify (external) event handlers

Guess you could also tell the control to fire such event handlers programmatically

**Comment by Viglino** [comment]
You can, just add an interaction to the toggle and it'll get `change:active` when activated...
In the example https://viglino.github.io/ol-ext/examples/bar/map.control.toggle.html : 
```
pedit.getInteraction().on('change:active', (e) => console.log(e))
```
