### ISSUE TITLE
loop filter.mask feature 

### ISSUE THREAD

**Issue by MarcPhi** [Viglino/ol-ext#657]
Is there a option to loop the filter.mask() feature around the globe the same way like vector layer features loop?
At the moment its not really possible (correct me if im wrong) to mask an area thats crossing the antimeridian correct.

**Comment by Viglino** [comment]
Yet the mask is only drawn in the current world.
I think you can cross the origin but the mask is only drawn at the coordinates in the polygon geometry and it is not repeated in the other worlds.
I'll try to see what can be done...

**Comment by theheckwr** [comment]
Any updates on this?
I've stumbled over this issue while recognizing the same "problem" with the `filter.crop()` feature...

**Comment by Viglino** [comment]
😞  Sorry I'm ma little busy yet, but I'll try to have a look at it asap...

**Comment by Viglino** [comment]
Should world now with `wrapX` option set to `true`
See example: https://viglino.github.io/ol-ext/examples/filter/map.filter.crop.html

**Comment by andreighh** [comment]
Thank you! It's an amazing library.

**Comment by theheckwr** [comment]
I'm sorry to bother you again about this issue, but I found, that it doesn't always wrap.
As you can see below here the Crop isn't wrapped.
![grafik](https://github.com/Viglino/ol-ext/assets/22587394/85112c5f-1b0e-48c4-a182-367a00fe3427)
I managed to narrow it down a little bit: If I move the map in x-direction so that the right or left edge are in the center, than it starts to wrap. but as soon as one whole overlay is in the picture its the same as in the picture above.

I managed to fix it by moving the `+1` to the start parameter, but be aware, that was pure trial and error as I have no knowledge how this really works. 
File: `ol-ext/filter/Mask.js`, line 114
```js
    var start = Math.floor((extent[0] + fWidth - worldExtent[0]) / worldWidth) + 1;
    var end = Math.floor((extent[2] - fWidth - worldExtent[2]) / worldWidth);
```
Thanks for helping with a correct solution!

**Comment by theheckwr** [comment]
Okay, I'm really sorry.
But further checking the dependencies managed to solve it. It appears that when update the dependencies I got really messed up.
Sorry for all confusion, it works properly now! Thanks for the amazing library! Keep up the great work!
