### ISSUE TITLE
Deactivate all Editbar and Bar selection

### ISSUE THREAD

**Issue by ngjiajunsg** [Viglino/ol-ext#849]
i have add editbar and some bar control

but seem like when i click editbar the extra bar does not collapse and deactivate the selection.

https://codepen.io/ngjiajun/pen/KKRdvqJ

for the extra bar control. i use ` edit.deactivateControls();` to deactivate but for the extra bar control how i use the editbar to deactivate the extra bar controls

**Comment by Viglino** [comment]
I think that the issue is the edit bar is `toggleOne` this means that almost one is toggle (and active).

You have to activate one (at least). Try to activate the selection when your control is clicked. 
You also have to listen to all edit control activation to disable your control on activate...

You can also add extra buttons directly in the edit bar (thus they are toggle wit it).

**Comment by ngjiajunsg** [comment]
But if my edit bar i already add new bar to it. but seem like both EditBar and New bar is control activation is not sync together. resulted i have BOTH drawing and selection call together.

> You can also add extra buttons directly in the edit bar (thus they are toggle wit it).

as for the above. i try to add the extra bar into edit bar but does not seem to work.

**Comment by Viglino** [comment]
You have to add button directly in the edit bar (not in a bar in the editbar)...

**Comment by ngjiajunsg** [comment]
can i check if there is a possible to check new Bar control activation and disable it when EditBar control is activate? if yes how should i do it?
