### ISSUE TITLE
Svelte and CJS vs ES module issue

### ISSUE THREAD

**Issue by SimonSchneider** [Viglino/ol-ext#863]
Trying to import `ol-ext` in a svelteKit project gives the following error:
```
ol-ext doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```
Given that OpenLayers defines `"type": "module"` ([link](https://github.com/openlayers/openlayers/blob/7dac035a3fce440844f54d7ee774ab01fc7907ea/package.json#L33)) maybe it'd be reasonable to `ol-ext` to do the same?

**Comment by SimonSchneider** [comment]
That was fast, thank you very much! 

Will check if the typescript definitions require `"type": "module"`, thanks!

Any idea on when a new release will be available?

**Comment by Viglino** [comment]
I've published a 4.0.1. 
Tell me if it runs.

**Comment by Isti115** [comment]
This breaks webpack for me with the following error:

> ERROR in ./node_modules/ol-ext/layer/GeoImage.js 5:0-43
Module not found: Error: Can't resolve 'ol/layer/Image' in '/home/isti/prog/collmot/skybrush-io/live/node_modules/ol-ext/layer'
Did you mean 'Image.js'?
BREAKING CHANGE: The request 'ol/layer/Image' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

I guess that if you want to keep the `"type": "module"` option, then file extensions will have to be added to all imports.

**Comment by Viglino** [comment]
See #868

**Comment by SimonSchneider** [comment]
Sorry for the delay, I've tested it and 4.0.1 has been working great

**Comment by Viglino** [comment]
@SimonSchneider 
> Sorry for the delay, I've tested it and 4.0.1 has been working great

It seems that extension is required when using "type": "module"

**Comment by SimonSchneider** [comment]
I'm unsure, when I tested a local branch I only had issues with the gulpfile needing to be changed to be `.mjs` the rest seemed to work.
For my project the addition of `"type": "module"` which you released resolved the issue.

**Comment by Isti115** [comment]
I have quickly grepped through the source and didn't see any reason not to simply just add the `.js` extension to all the import declarations, so I executed `s/(import .* from) ('.*)'/$1 $2.js'/g` in the repo and created a pull request from it (#869), so in case you agree with this approach, @Viglino, you can just merge it right away.

**Comment by Viglino** [comment]
@Isti115 That's what I planned to do!
you beat me 🚀

**Comment by Viglino** [comment]
ol-ext@4.0.2 is out

**Comment by Siedlerchr** [comment]
For what it worth, in the types-ol-ext repo I used the following addtion to the webpack to compile the examples:
```

  {
        test: /\.m?js/,
        type: "javascript/auto",
      },
      {
        test: /\.m?js/,
        resolve: {
          fullySpecified: false,
        },
      },
    ],
```

**Comment by Viglino** [comment]
@Siedlerchr fixed duplicated extension (there was some more)

**Comment by Isti115** [comment]
Ouch, sorry, that's my bad, I should've checked for already present extensions before running the RegEx replacement, but for some reason I assumed that all imports where extensionless so far.
