### ISSUE TITLE
Enable drawing/showing line and polygon data as search results from geocoders (OSM Nominatim)

### ISSUE THREAD

**Issue by darkscript** [Viglino/ol-ext#94]
Could it be useful to draw polygons and lines provided as search results by geocoders such as Nominatim?
![image](https://user-images.githubusercontent.com/13992858/38149448-310bb140-3463-11e8-9cc7-c2e3899a5bd9.png)
see [here](https://www.openstreetmap.org/relation/192799#map=5/3.820/47.373).

**Comment by Viglino** [comment]
Hello,

I've added a new `polygon` option to the SearchNominatim control to get the geometry.
It's up to you to display it on the map. See the [search nominatim example](http://viglino.github.io/ol-ext/examples/search/map.control.searchnominatim.html). 
I've also added an animation to wait while loading (because it may be a bit long when loading large data sets).

@+

**Comment by darkscript** [comment]
Hi,

That was fast implemented and works great. I test both lines and polygons and its works. Thanks much
